--D --
-- List all the mechanics that worked on a car between 12 June and 22 June of 2022 --

SELECT DISTINCT MECHANIC.STAFF_ID, MECHANIC.M_NAME, MECHANIC.M_SURNAME
FROM MECHANIC, JOB
WHERE JOB.J_DATE BETWEEN '2022-06-12' AND '2022-06-22';


-- E --
-- Provide a list of Customer names and emails for all the Clients that own a Ford Fiesta 2014 --

SELECT CLIENT.C_ID, CLIENT.C_NAME, CLIENT.C_SURNAME, CLIENT.C_EMAIL
FROM CLIENT
FULL OUTER JOIN CAR
ON CAR.CLIENT_ID = CLIENT.C_ID
WHERE CAR.C_BRAND = 'Ford' AND CAR.C_MODEL = 'Fiesta' AND CAR.C_YEAR = '2014';


-- F --
-- List the unique number of clients each mechanic has serviced a car for --

SELECT MECHANIC.STAFF_ID, MECHANIC.M_NAME, MECHANIC.M_SURNAME, COUNT(DISTINCT CLIENT.C_ID) 
AS [NUMBER OF CLIENTS]
FROM MECHANIC, JOB, CAR, CLIENT 
WHERE JOB.STAFF_ID = MECHANIC.STAFF_ID 
		AND JOB.CAR_ID = CAR.CAR_ID
		AND CAR.CLIENT_ID = CLIENT.C_ID
GROUP BY MECHANIC.STAFF_ID, MECHANIC.M_NAME, MECHANIC.M_SURNAME;
---------------- OR --------------------------
SELECT MECHANIC.STAFF_ID, MECHANIC.M_NAME, MECHANIC.M_SURNAME, COUNT(DISTINCT CLIENT.C_ID) 
AS [NUMBER OF CLIENTS]
FROM MECHANIC
INNER JOIN JOB
ON MECHANIC.STAFF_ID = JOB.STAFF_ID
INNER JOIN CAR
ON JOB.CAR_ID = CAR.CAR_ID
INNER JOIN CLIENT
ON CAR.CLIENT_ID = CLIENT.C_ID
GROUP BY MECHANIC.STAFF_ID, MECHANIC.M_NAME, MECHANIC.M_SURNAME;
---------------- OR (SOLUTON) --------------------------
Select mech.name, count(clientID)
from Mech 
Join service 
on mechID
join car
on carID
join CLIENT
on clientID
group by mech.name

-- G --
-- How many mechanics have received an average rating equal to or higher than 5 --

SELECT JOB.STAFF_ID, AVG(JOB.RATING) AS [AVG_RATING]
FROM MECHANIC
INNER JOIN JOB
ON MECHANIC.STAFF_ID = JOB.STAFF_ID
GROUP BY JOB.STAFF_ID
HAVING AVG(JOB.RATING) >= 5;
---------------- OR --------------------------
SELECT STAFF_ID, AVG(RATING) AS AVERAGE_RATING
FROM JOB
GROUP BY STAFF_ID
HAVING AVG(RATING) >= 5;


-- H --
-- Which mechanic received the highest average service rating --

SELECT MECHANIC.STAFF_ID, AVG(JOB.RATING) AS [AVG_RATING]
FROM MECHANIC
INNER JOIN JOB
ON MECHANIC.STAFF_ID = JOB.STAFF_ID
GROUP BY MECHANIC.STAFF_ID
ORDER BY AVG_RATING DESC;
---------------- OR --------------------------
SELECT JOB.STAFF_ID, AVG(RATING) AS AVERAGE_RATING
FROM JOB, MECHANIC
GROUP BY JOB.STAFF_ID
ORDER BY AVERAGE_RATING DESC;