DROP TABLE JOB;
DROP TABLE CAR;
DROP TABLE MECHANIC;
DROP TABLE CLIENT;

CREATE TABLE CLIENT(
	C_ID INT UNIQUE NOT NULL,
	C_NAME VARCHAR(255) NOT NULL,
	C_SURNAME VARCHAR(255) NOT NULL,
	C_EMAIL VARCHAR(255),
	C_CONTACT_NUMBER VARCHAR(12),
	PRIMARY KEY(C_ID)
);

CREATE TABLE MECHANIC(
	STAFF_ID INT UNIQUE NOT NULL,
	M_NAME VARCHAR(255) NOT NULL,
	M_SURNAME VARCHAR(255) NOT NULL,
	M_EMAIL VARCHAR(255),
	M_CONTACT_NUMBER VARCHAR(12),
	PRIMARY KEY(STAFF_ID)
);

CREATE TABLE CAR(
	CAR_ID INT UNIQUE NOT NULL,
	VIN VARCHAR(17) UNIQUE NOT NULL,
	CLIENT_ID INT NOT NULL,
	C_BRAND VARCHAR(255) NOT NULL,
	C_MODEL VARCHAR(255) NOT NULL,
	C_YEAR VARCHAR(4) NOT NULL,
	C_REG_NUMB VARCHAR(8) NOT NULL,
	PRIMARY KEY(CAR_ID),
	FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(C_ID)
);

CREATE TABLE JOB(
	J_ID INT UNIQUE NOT NULL,
	STAFF_ID INT NOT NULL,
	CAR_ID INT NOT NULL,
	VIN VARCHAR(17) NOT NULL,
	J_DATE DATE NOT NULL,
	J_TOTAL DECIMAL(38,2),
	RATING INT,
	PRIMARY KEY(J_ID),
	FOREIGN KEY (STAFF_ID) REFERENCES MECHANIC(STAFF_ID),
	FOREIGN KEY (VIN) REFERENCES CAR(VIN),
	FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID)
);